---
swagger: "2.0"
basePath: /v1
info:
  description: Builder of the Things (bott)
  title: APIs of the bott
  version: 1.0.0
schemes:
- http
securityDefinitions:
  withToken:
    type: apiKey
    in: header
    name: bott-token
security:
  - withToken: []
consumes:
  - application/json
produces:
  - application/json
paths:
  # /deployXiIOT:
    # post:
  # /deployCloudMgmt:
    # post:
  /tenant:
    post:
      tags: 
        - setup
      parameters:
        - name: spec
          in: body
          required: true
          schema:
            $ref: '#/definitions/tenant'
      responses:
        200:
          description: The tenant id
          schema:
            $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /user:
    post:
      tags: 
        - setup
      security: [] # No security
      parameters:
        - name: spec
          in: body
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        200:
          description: The User ID
          schema:
            $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /user/{tenant}/{username}:
    get:
      tags:
        - setup
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: username
          in: path
          description: username
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: Get the user info
          schema:
            type: object
            $ref: '#/definitions/user'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /role:
    post:
      tags: 
        - setup
      parameters:
        - name: spec
          in: body
          required: true
          schema:
            $ref: '#/definitions/role'
      responses:
        200:
          description: The Role ID
          schema:
            $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /context:
    post:
      tags:
        - iot
      parameters:
        - name: spec
          in: body
          required: true
          schema:
            $ref: "#/definitions/context"
      responses:
        200:
          description: context id
          schema:
            $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /context/list:
    get:
      tags:
        - iot
      operationId: listContexts
      parameters:
        - name: project
          description: project name
          in: query
          type: string
      responses:
        200:
          description: context id
          schema:
            type: array
            items: 
              $ref: '#/definitions/context'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /context/{tenant}/{project}/{name}:
    get:
      tags:
        - iot
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: name
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: Get the context info
          schema:
            type: object
            $ref: '#/definitions/context'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - iot
      operationId: deleteContext
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: name
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: Context deleted
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /cloudMgmtEndpoint:
    post:
      tags:
        - iot
      operationId: createCloudMgmtEndpoint
      parameters:
        - name: spec
          in: body
          required: true
          schema:
            $ref: "#/definitions/cloudMgmtEndpoint"
      responses:
        200:
          description: Cloud mgmt endpoint id
          schema:
            $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /cloudMgmtEndpoint/{tenant}/{project}/{contextName}/{name}:
    get:
      tags:
        - iot
      operationId: getCloudMgmtEndpoint
      parameters:
        - name: name
          in: path
          description: cloud management endpoint name
          type: string
          required: true
          maxLength: 128
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: contextName
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: Get the context info
          schema:
            type: object
            $ref: '#/definitions/cloudMgmtEndpoint'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - iot
      operationId: deleteCloudMgmtEndpoint
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: contextName
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
        - name: name
          in: path
          description: cloud management endpoint name
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: End point deleted
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /cloudMgmtEndpoint/list:
    get:
      tags:
        - iot
      operationId: listCMEndpoints
      parameters:
        - name: project
          description: project name
          in: query
          type: string
      responses:
        200:
          description: List of cloud mgmt endpoints
          schema:
            type: array
            items: 
              $ref: '#/definitions/cloudMgmtEndpoint'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /context/deployApps:
    post:
      tags:
        - iot
      operationId: createApps
      parameters:
        - name: spec
          in: body
          required: true
          schema:
            $ref: '#/definitions/deployAppsSpec'
      responses:
        200:
          description: The context id in which the apps were deployed
          schema:
            type: array
            items: 
              $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /app/{tenant}/{project}/{contextName}/{name}:
    put:
      tags:
        - iot
      operationId: UpdateApp
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: contextName
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
        - name: name
          in: path
          description: app name
          type: string
          maxLength: 128
          required: true
        - name: update
          in: body
          description: The update to the app
          schema:
            type: object
            properties:
              chartVersion:
                type: string
                maxLength: 16
              chartValues:
                type: string
      responses:
        200:
          description: App id
          schema:
            $ref: "#/definitions/entity"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - iot
      operationId: deleteApp
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: contextName
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
        - name: name
          in: path
          description: app name
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: End point deleted
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    get:
      tags:
        - iot
      operationId: getApp
      parameters:
        - name: tenant
          in: path
          description: tenant name
          type: string
          required: true
          maxLength: 128
        - name: project
          in: path
          description: project name
          type: string
          maxLength: 128
          required: true
        - name: contextName
          in: path
          description: context name
          type: string
          maxLength: 128
          required: true
        - name: name
          in: path
          description: app name
          type: string
          maxLength: 128
          required: true
      responses:
        200:
          description: Get the context info
          schema:
            type: object
            $ref: '#/definitions/appDeployment'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /app/list:
    get:
      tags:
        - iot
      operationId: listApps
      parameters:
        - name: project
          description: project name
          in: query
          type: string
      responses:
        200:
          description: List of apps
          schema:
            type: array
            items: 
              $ref: '#/definitions/appDeployment'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  entity:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        maxLength: 1024
  cloudMgmtEndpoint:
    type: object
    required:
      - name
      - url
      - userID
      - password
      - contextID
    properties:
      id: 
        type: string
        maxLength: 1024
      name: 
        type: string
        maxLength: 128
      url:
        type: string
      userID:
        type: string
        maxLength: 128
      password:
        type: string
        maxLength: 128
      contextID:
        type: string
        maxLength: 1024
  k8sDeployment:
    type: object
    required:
      - k8sNamespace
      - k8sConfigJson 
    properties:
      k8sNamespace:
        type: string
      k8sConfigJson:
        type: string
  edgeMeta:
    type: object
    properties:
      sappDeploy:
        type: boolean
      sappBucket:
        type: string
      sappBucketRegion:
        type: string
      sappProjectName:
        type: string
      sappProjectID:
        type: string
      datasourceDeploy:
        type: boolean
      datapipelineDeploy:
        type: boolean
      edgeID:
        type: string
      infraType:
        type: string
  appDeployment:
    type: object
    required:
      - name
      - chartVersion
      - k8sDeployment
      - contextID
      - status
      - appType
    properties:
      id: 
        type: string
        maxLength: 1024
      contextID:
        type: string
        maxLength: 1024
      name: 
        type: string
        maxLength: 128
      chartVersion: 
        type: string
        maxLength: 16
      chartValues:
        type: string
      k8sDeployment:
        $ref: '#/definitions/k8sDeployment'
      edgeMeta:
        $ref: '#/definitions/edgeMeta'
      status:
        type: string
      appName:
        type: string
        maxLength: 256
      appType:
        type: string
        maxLength: 16
      tags:
        type: string
        maxLength: 512
      cloudType:
        type: string
        maxLength: 16
      instanceType:
        type: string
        maxLength: 64
  deployAppInfo:
    type: object
    properties:
      tags:
        type: string
        maxLength: 512
      cloudType:
        type: string
        maxLength: 16
      instanceType:
        type: string
        maxLength: 64
      chartVersion:
        type: string
        maxLength: 16
      chartValues:
        type: string
      k8sInfo:
        type: object
        $ref: '#/definitions/k8sDeployment'
      edgeMeta:
        $ref: '#/definitions/edgeMeta'
  deployAppsSpec:
    type: object
    required:
      - name
      - contextID
      - appType
    properties:
      name:
        type: string
        maxLength: 128
      contextID:
        type: string
        maxLength: 1024
      appType:
        type: string
        maxLength: 16
      apps:
        type: array
        items: 
          $ref: '#/definitions/deployAppInfo'
  context:
    type: object
    required:
      - name
      - project
    properties:
      id: 
        type: string
        maxLength: 1024
      name:
        type: string
        maxLength: 128
      project:
        type: string
        maxLength: 128
      appDeploymentIDs:
        type: array
        items: 
          type: string
      cloudMgmtEndpointID:
        type: string
  user:
    type: object
    required:
      - username
      - email
      - password
      - name
    properties:
      id: 
        type: string
        maxLength: 1024
      username:
        type: string
        maxLength: 128
      email:
        type: string
        maxLength: 256
      password:
        type: string
      name:
        type: string
      role:
        type: string
      tenant:
        type: string
        maxLength: 128
  role:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        maxLength: 128
  tenant:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        maxLength: 128
  principal:
    type: object
    required:
      - username
      - tenant
      - role
    properties:
      username:
        type: string
        maxLength: 128
      role:
        type: string
        maxLength: 128
      tenant:
        type: string
        maxLength: 128