apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
data:
  s3-bucket: sherlock-dev-releases
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: operator-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: operator
      labels:
        app: operator
    spec:
      containers:
      - name: operator
        image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/edgecomputing/sherlock-cloud-operator:21
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: accessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: secretAccessKey
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: s3-bucket
        ports:
        - containerPort: 9000
        command:
        - sh
        - -c
        - "exec /operator/operator \
          --s3bucket=$S3_BUCKET \
          --logtostderr \
          -v 3"
---
kind: Service
apiVersion: v1
metadata:
  name: operator-svc
spec:
  selector:
    app: operator
  ports:
  - name: backend-port
    port: 9000
    protocol: TCP
    targetPort: 9000
